### ISSUE TITLE
data class and objects

### ISSUE THREAD

**Issue by jmfayard** [Zhuinden/guide-to-kotlin#11]
I now have writing rights but I prefer to open an issue about this. 

Re: https://github.com/Zhuinden/guide-to-kotlin/wiki/2.)-Basic-Kotlin-Features#data-classes

For me `data class with zero parameters` is simply an `object`. 

`object` gives you the right `toString()`, `equals()` and `hashCode()`. 

This happens most frequently in the context of a sealed class

```
sealed class Cmd

data class Reset(val value: Int) : Cmd()

// ERROR: Data Class must have at least one primary constructor parameter
data class Increment : Cmd()

// BAD: Decrement() != Decrement()
class Decrement : Cmd()
```

The correct thing to do here is to use an `object` and JetBrains actually has a quick-fix for it:

```kotlin
sealed class Cmd
data class Reset(val value: Int) : Cmd()
object Increment : Cmd()
object Decrement : Cmd()
```

And JetBrains actually made a quick-fix for that!

![image](https://user-images.githubusercontent.com/459464/50600903-da3e6300-0eb2-11e9-8893-25919d9e66de.png)

**Comment by Zhuinden** [comment]
> object gives you the right toString(), equals() and hashCode().

No it doesn't, the `toString()` will differ after process death because it includes system level hashcode and it breaks no-arg fragment key tags across process death if you use `toString()` as a fragment tag directly.

If you check the thread on the Kotlin forums, nobody cares about it, but the last 3 posts are me bitching about the removal of no-arg data classes.

Therefore the `placeholder: String = ""` is the most reasonable way to get consistent tags across android processes.

This is why I don't use `object` for it, considering if I said that here, I'd have to use big red letters in Simple-Stack saying "BTW PLEASE DON'T USE OBJECTS FOR THIS BECAUSE IT WILL BREAK YOUR FRAGMENT TAGS, PLEASE NAG THE KOTLIN GUYS TO FIX THEIR LANGUAGE", but I didn't do that; although tbh I probably should.

Either way, it doesn't behave like no-arg `@AutoValue` classes, which is the actual behavior I would be aiming for here.

**Comment by jmfayard** [comment]
Ah, that's your use case. Got it!

**Comment by Zhuinden** [comment]
Technically I could say "objects would normally be preferred but" considering this guide is more general purpose than Android-only.

I'll edit it a bit later.

**Comment by jmfayard** [comment]
@Zhuinden Please add your use-case here, I hope they fix this problem it bugs me too. 
https://youtrack.jetbrains.com/issue/KT-4107

I've used another work-around 

```kotlin
object NoArgTag : FixToString() 
// NoArgTag.toString() == "NoArgTag"

/** See https://youtrack.jetbrains.com/issue/KT-4107 **/  
abstract class FixToString {
      private val simpleName : String by lazy { this::class.simpleName ?: super.toString() }
      override fun toString() = simpleName
}
```

**Comment by Zhuinden** [comment]
I actually wouldn't use `simpleName` either because then you have to use a proguard-rule. It might be more advisable to use `class.name` instead, as that also includes packages and therefore cannot end up duplicate.
